version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install            
    build:
        commands:
            # mkdir artifacts
            # create staging deployment package
            # mkdir artifacts/stg
            - echo Building react application...
            - react-scripts build
            - printenv
#    post_build:
#        commands:
#            - serverless remove --stage test -v

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
