version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - npm install            
    build:
        commands:
            # mkdir artifacts
            # create staging deployment package
            # mkdir artifacts/stg
            - pwd
            - cd carapp
            - pwd
            - echo Building react application...
            - printenv > .env.stg
            - npm run build:stg
#    post_build:
#        commands:
#            - serverless remove --stage test -v

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
