version: 0.2

phases: 
    install:
        #runtime-versions:
        #    nodejs: 12
        commands:
            - echo installing node 12...
            - curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt install -y nodejs
    pre_build:
        commands:
            - echo install dependencies...
            - npm install
    build:
        commands:
            - echo Building react application...
            - printenv > .env.stg
            - npm run build:stg

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
