version: 0.2

phases: 
    install:
        #runtime-versions:
        #    nodejs: 12
        commands:
            - echo installing node 12...
            - curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt install -y nodejs
    pre_build:
        commands:
            - echo install dependencies...
            - npm install -g react@16.12.0 react-scripts@3.2.0 env-cmd@10.0.1
            - npm install
    build:
        commands:
            - echo Building react application...
            - printenv > .env.stg
            - env-cmd --file .env.stg react-scripts build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
