version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            #- echo installing node 12...
            #- curl -sL https://deb.nodesource.com/setup_12.x | bash -
            #- apt install -y nodejs
            - npm install -g react-scripts
    #pre_build:
    #    commands:
    #        - echo install dependencies...
            #- npm install -g create-react-app@3.2.0 env-cmd@10.0.1
    build:
        commands:
            - echo Building react application...
            #- printenv > .env.stg
            #- env-cmd --file .env.stg react-scripts build
            - react-scripts build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
